# Generated by Django 2.2.7 on 2020-01-31 03:23

from django.db import migrations


def conv_to_titlecase(apps, schema_editor):
    Product = apps.get_model("main", "Product")

    for prod in Product.objects.all():
        prod.name = prod.name.title()
        prod.save()


class Migration(migrations.Migration):
    """
    This migration was created by this:
    >> ./manage.py makemigrations main --empty -n THE_MIGRATION_NAME
    """

    dependencies = [
        ("main", "0006_producttagname_40"),
    ]

    operations = [
        # The 1st: being used to modify the objects before going into DB.
        # The 2nd: a reverse operation (what to do when "un-apply" migrations)
        migrations.RunPython(
            code=conv_to_titlecase, reverse_code=migrations.RunPython.noop
        )
    ]
